django_library_manager/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', views.LoginView.as_view(template_name='library/login.html'), name='login'),
    path('', include('library.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
]

library/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as generic_views


app_name = 'library'
urlpatterns = [
    path('', views.home, name='home'),
    path('bad_data/', views.bad_data, name='bad_data'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('login/', generic_views.LoginView.as_view(template_name='library/login.html'), name='login'),
    path('logout/', views.log_me_out, name='log_me_out'),
    path('books/', views.BooksView.as_view(), name='books'),
    path('books/new/', views.NewBook.as_view(), name='new_book'),
    # path('books/modify/', views.ModifyBook.as_view(), name='modify_book'),
    # path("books/modify/<path:book_id>/", views.book_modifier, name='book_modifier'),
    # path('books/delete/', views.DeleteBook.as_view(), name='delete_book'),
    path("books/<path:book_id>/", views.BookInfo.as_view(), name='book_info'),
    path('locations/', views.LocationsView.as_view(), name='locations'),
    path('locations/new/', views.NewLocation.as_view(), name='new_location'),
    path("locations/<path:location_id>/", views.LocationInfo.as_view(), name='location_info'),
    # path('locations/delete/', views.DeleteLocation.as_view(), name='delete_location'),
    path('loans/', views.LoansView.as_view(), name='loans'),
    path('loans/loan/', views.LoanBook.as_view(), name='loan_book'),
    path('loans/return/', views.ReturnBook.as_view(), name='return_book'),
]

library/models.py
from django.db import models

# Create your models here.


class Location(models.Model):
    address = models.CharField(max_length=100)
    room = models.CharField(max_length=100)
    furniture = models.CharField(max_length=100)
    details = models.CharField(max_length=100)
    created = models.DateTimeField('date created')
    username = models.CharField(max_length=100)
    
    def __str__(self):
        return self.address


class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    genre = models.CharField(max_length=100)
    publisher = models.CharField(max_length=100)
    isbn = models.CharField(max_length=100)
    publish_date = models.CharField(max_length=50)
    purchase_date = models.CharField(max_length=50)
    location = models.ForeignKey(Location, on_delete=models.DO_NOTHING, null=True)
    loaned = models.BooleanField(default=False)
    created = models.DateTimeField('date created')
    modified = models.DateTimeField('date modified', null=True)
    username = models.CharField(max_length=100)
    
    def __str__(self):
        return self.title


class Loan(models.Model):
    book = models.ForeignKey(Book, on_delete=models.DO_NOTHING)
    lender = models.CharField(max_length=100)
    borrower = models.CharField(max_length=100)
    loan_date = models.DateTimeField('date of loan')
    return_date = models.DateTimeField('date of return', null=True)
    
    def __str__(self):
        return self.recipient

library/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.http import Http404
from django.views import generic
from django.views import View
from django.middleware.csrf import CsrfViewMiddleware
from django.utils import timezone
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import logout
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import gettext as _
# Create your views here.


from .models import *

# Create your views here.
book_table_headers = {
    'title': _('Title'),
    'author': _('Author'),
    'genre': _('Genre'),
    'publisher': _('Publisher'),
    'isbn': _('ISBN'),
    'publish_date': _('Publish date'),
    'purchase_date': _('Purchase date'),
    'loaned': _('On Loan')
}
location_table_headers = {
    'address': _('Address'),
    'room': _('Room'),
    'furniture': _('Furniture'),
    'details': _('Details'),
}
loan_table_headers = {
    'book': _('Book'),
    'borrower': _('Borrower'),
    'loan_date': _('Loan Date'),
    'return_date': _('Return Date'),
}


def bad_data(request):
    return render(request, 'library/bad_data.html')


class SignUp(View):
    
    def get(self, request):
        form = UserCreationForm()
        return render(request, 'library/signup.html', {'form': form})
    
    def post(self, request):
        try:
            form = UserCreationForm(request.POST)
            if form.is_valid():
                form.save()
                username = form.cleaned_data.get('username')
                raw_password = form.cleaned_data.get('password1')
                user = authenticate(username=username, password=raw_password)
                login(request, user)
                return redirect('/')
            else:
                return render(request, 'library/signup.html', {'form': form})
        except Exception:
            return redirect('/bad_data/')


@login_required(login_url='/login/')
def log_me_out(request):
    try:
        logout(request)
        return redirect('/')
    except Exception:
        return redirect('/bad_data/')


@login_required(login_url='/login/')
def home(request):
    try:
        page_title = _('Please Login to Your Library Manager')
        # header = _('Welcome to your libary {}'.format(request.user.username))
        books = Book.objects.filter(username=request.user.username).count()
        loans = Book.objects.filter(username=request.user.username, loaned=True).count()
        context = {
            'page_title': page_title,
            # 'my_header': header,
            'books': books,
            'loans': loans,
        }
        return render(request, 'library/home.html', context)
    except Exception:
        return redirect('/bad_data/')


class BooksView(LoginRequiredMixin, generic.ListView):
    login_url = '/login/'
    template_name = 'library/show_books.html'
    title = _("All Books")
    bottom_bar = [
        {'href': '/books/new/', 'text': _('New')},
    ]
    
    def get_queryset(self):
        pass
    
    def get_context_data(self, *, object_list=None, **kwargs):
        all_books = Book.objects.order_by('author')
        context = super().get_context_data(**kwargs)
        context['page_title'] = self.title
        #  context['my_header'] = header,
        context['table_headers'] = book_table_headers
        context['books'] = all_books
        context['bottom_bar'] = self.bottom_bar
        return context


class BookInfo(LoginRequiredMixin, View):
    login_url = '/login/'
    model_fields = [
        'title', 'author', 'genre', 'publisher',
        'isbn', 'publish_date', 'purchase_date', 'location']
    
    def get(self, request, book_id, **kwargs):
        try:
            book = Book.objects.get(pk=book_id)
            # prepare location drop-down data
            all_locations = Location.objects.order_by('address')
            my_locations = []
            for location in all_locations:
                value = location.id
                text = location.address + ' - ' + location.room + ' - ' + location.furniture + ' - ' + location.details
                data = {'value': value, 'text': text}
                my_locations.append(data)
            # set response's context
            context = {
                'book': book,
                'all_locations': my_locations,
            }
            return render(request, 'library/book_info.html', context)
        except Exception as e:
            print("[!] Error processing request: {}".format(e))
            return redirect('/bad_data/')

    def post(self, request, book_id):
        # check csrf
        request.csrf_processing_done = False
        reason = CsrfViewMiddleware().process_view(request, None, (), {})
        if reason is not None:
            return reason
        # for k, v in request.POST.items():
        #    print('\t> {}: {}'.format(k, v))
        # SELECT ACTION
        if request.POST.get('action') == 'modify':
            book = Book.objects.get(pk=book_id)
            for field in self.model_fields:
                book.__dict__[field] = request.POST.get(field, None)
            # update modification date field
            book.modified = timezone.now()
            book.save()
        elif request.POST.get('action') == 'delete':
            # deleting db model entry
            Book.objects.filter(pk=book_id).delete()
        else:
            return redirect('/bad_data/')
        return redirect('/books/')


class NewBook(LoginRequiredMixin, View):
    login_url = '/login/'
    model_fields = [
        'title', 'author', 'genre', 'publisher',
        'isbn', 'publish_date', 'purchase_date', 'location']
    
    def get(self, request):
        try:
            all_locations = Location.objects.order_by('id')
            my_locations = []
            for location in all_locations:
                value = location.id
                text = location.address + ' - ' + location.room + ' - ' + location.furniture + ' - ' + location.details
                data = {'value': value, 'text': text}
                my_locations.append(data)
            context = {
                # 'my_header': header,
                'all_locations': my_locations,
            }
            return render(request, 'library/new_book.html', context)
        except Exception:
            return redirect('/bad_data/')
    
    def post(self, request):
        try:
            # check csrf
            request.csrf_processing_done = False
            reason = CsrfViewMiddleware().process_view(request, None, (), {})
            if reason is not None:
                return reason
            # set user input data
            book = Book()
            print("[#] New Book:")
            for field in self.model_fields:
                book.__dict__[field] = request.POST.get(field, '')
                print("\t> {}: {}".format(field, book.__dict__[field]))
            # set system data
            book.loaned = False
            book.username = request.user.username
            book.created = timezone.now()
            # add model to db
            book.save()
            return redirect('/books/')
        except Exception:
            return redirect('/bad_data/')


class LocationsView(LoginRequiredMixin, generic.ListView):
    login_url = '/login/'
    template_name = 'library/show_locations.html'
    title = _("All Locations")
    bottombar_links = [
        {'href': '/locations/new/', 'text': _('New')},
    ]
    
    def get_queryset(self):
        pass
    
    def get_context_data(self, *, object_list=None, **kwargs):
        all_locations = Location.objects.order_by('address')
        context = super().get_context_data(**kwargs)
        context['page_title'] = self.title
        # context['my_header'] = header,
        context['bottom_bar'] = self.bottombar_links
        context['table_headers'] = location_table_headers
        context['locations'] = all_locations
        return context


class NewLocation(LoginRequiredMixin, View):
    login_url = '/login/'
    location_fields = ['address', 'room', 'furniture', 'details']
    
    def get(self, request):
        try:
            return render(request, 'library/new_location.html')
        except Exception:
            return redirect('/bad_data/')
    
    def post(self, request):
        try:
            # check csrf
            request.csrf_processing_done = False
            reason = CsrfViewMiddleware().process_view(request, None, (), {})
            if reason is not None:
                return reason
            # new model instance
            location = Location()
            # add user input
            for field in self.location_fields:
                location.__dict__[field] = request.POST.get(field, '')
            # add system data
            location.created = timezone.now()
            # add instance to db
            location.save()
            return redirect('/locations/')
        except Exception:
            return redirect('/bad_data/')


class LocationInfo(LoginRequiredMixin, View):
    login_url = '/login/'
    title = _("Location Info")
    model_fields = ['address', 'room', 'furniture', 'details']
    
    def get(self, request, location_id):
        try:
            location = Location.objects.get(pk=location_id)
            context = {
                'location': location,
                'page_title': self.title,
                'table_headers': location_table_headers,
                # 'button_text': self.title,
            }
            return render(request, 'library/location_info.html', context)
        except Exception as e:
            print("[!] Error processing request: {}".format(e))
            return redirect('/bad_data/')
    
    def post(self, request, location_id):
        try:
            # check csrf
            request.csrf_processing_done = False

library/templates/library/bad_data.html
{% extends "library/base.html" %}
{% block content %}
{% load i18n %}
<!-- BAD DATA -->
	 <article style="border: 5px solid green">
		 <h1>{% trans 'Input data was not properly formatted.' %}</h1>
		 <h1>{% trans 'Change it and try again' %}</h1>
		 <h3>
	 </h3>
	</article>
	<p/>
	<p/>
	<div class="w3-container">
		<a href="/" class="w3-btn w3-border w3-border-blue" style="font-size:1.5vw">{% trans 'Back to the start' %}</a>
	</div>
{% endblock %}

library/templates/library/base.html
<!DOCTYPE html>
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">
<head>
    <meta charset="UTF-8">
    <title>{% trans page_title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" type="text/css" href="{% static 'library/style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
</head>
<body>
  <header>
    {% if user.is_authenticated %}
    <a class="user-name w3-cell w3-btn" href="{% url 'library:home' %}">{{user.username}}</a>
    {% endif %}
    <banner>{% trans 'My Library Manager' %}</banner>
  </header>
{% if user.is_authenticated %}
<!-- NAVBAR -->
<nav class=" navbar w3-cell-row w3-black">
    <a href="{% url 'library:books' %}" class="w3-container w3-cell w3-btn w3-mobile w3-hover-blue"
       >{% trans 'Books' %}</a>
    <a href="{% url 'library:locations' %}" class="w3-container w3-cell w3-btn w3-mobile w3-hover-blue"
       >{% trans 'Locations' %}</a>
    <a href="{% url 'library:loans' %}" class="w3-container w3-cell w3-btn w3-mobile w3-hover-blue" >{% trans 'Loans' %}</a>
</nav>
{% endif %}
{% block content %}{% endblock %}
{% if user.is_authenticated and bottom_bar%}
<div class=" bottom-bar w3-cell-row w3-black">
  {% for link in bottom_bar %}
    <a href="{{link.href}}" class="bottom_link w3-container w3-cell w3-btn w3-mobile w3-hover-green">{{link.text }}</a>
  {% endfor %}
</div>
{% endif %}
<script type="text/javascript" src = "{% static 'library/script.js' %}"></script>
</body>
</html>

library/templates/library/book_info.html
{% extends "library/base.html" %}
{% block content %}
{% load i18n %}
{% if book %}
    <div  class="w3-container small-font w3-teal">
      <div class="w3-container">
         <h2 align="center" >{% trans 'Book Information' %}</h2>
	  </div>
      <div class="w3-container " style="white-space:nowrap">
	  <form action="{% url 'library:book_info' book.id %}" method='post'>
		{% csrf_token %}
	  <input type='hidden' name='bookID' value='{{book.id}}'>
	  <label>{% trans 'Title' %}</label>
	  <input class="w3-input" type="text" name="title" value="{{book.title}}"/>
	  <label>{% trans 'Author' %}</label>
	  <input class="w3-input" type="text" name="author" value="{{book.author}}"/>
	  <label>{% trans 'Genre' %}</label>
	  <input class="w3-input" type="text" name="genre" value="{{book.genre}}"/>
	  <label>{% trans 'Publisher' %}</label>
	  <input class="w3-input" type="text" name="publisher" value="{{book.publisher}}"/>
	  <label>{% trans 'ISBN' %}</label>
	  <input class="w3-input" type="text" name="isbn" value="{{book.isbn}}"/>
	  <label>{% trans 'Publish date' %}</label>
	  <input class="w3-input" type="text" name="publish_date" value="{{book.publish_date}}"/>
	  <label>{% trans 'Purchase date' %}</label>
	  <input class="w3-input" type="text" name="purchase_date" value="{{book.purchase_date}}"/>
	  <label>{% trans 'Location' %}</label>
		<select class="w3-input" name="location_id">
			{% if all_locations %}
			{% for location in all_locations %}
			  {% if location.value == book.location_id %}
			<option value="{{ location.value }}" selected>{{ location.text }}</option>
			  {% else %}
			<option value="{{ location.value }}">{{ location.text }}</option>\n
			  {% endif %}
			{% endfor %}
			{% endif %}
		</select>
	  <div class="medium-font w3-container">
         <p>{% trans 'Added: '%}{{book.created}}</p>
		  <p>{% trans 'Modified: '%}{{book.modified}}</p>
	  </div>
	<div class="medium-font w3-cell-row w3-black">
  		<button type="submit" name="action" value="modify" class="w3-half w3-container w3-cell w3-btn w3-mobile w3-hover-green">
		{% trans 'Modify'%}</button>
		<button type="submit" name="action" value="delete" class="w3-half w3-container w3-cell w3-btn w3-mobile w3-hover-green">
		{% trans 'Delete'%}</button>
	</div>
	</form>
  </div>
</div>
{% endif %}
{% endblock %}

library/templates/library/choose_book.html
{% extends "library/base.html" %}
{% block content %}
{% load i18n %}
{% if books %}
<div class="w3-margin small-font">
  <form action="{% url 'library:loan_book'%}" method='post'>
  {% csrf_token %}
  <table id="info" class="w3-table-all w3-hoverable">
  {% if table_headers %}
  <tr class="choose-table w3-cyan">
    <th class="w3-hover-light-blue ">#</th>
    <th class="w3-hover-light-blue ">{{ table_headers.title }}</th>
    <th class="w3-hover-light-blue ">{{ table_headers.author }}</th>
    <th class="w3-hover-light-blue ">{{ table_headers.publisher }}</th>
    <th class="w3-hover-light-blue ">{{ table_headers.publish_date }}</th>
    <th class="w3-hover-light-blue ">{{ table_headers.purchase_date }}</th>
    <th class="w3-hover-light-blue ">{{ table_headers.loaned }}</th>
  </tr>
  {% endif %}
  {% for book in books %}
  <tr class="book-info w3-white ">
    <td> <input type='radio' name='bookID' value='{{ book.id }}'></td>
    <td>{{ book.title }}</td>
    <td>{{ book.author }}</td>
    <td>{{ book.publisher }}</td>
    <td>{{ book.publish_date }}</td>
    <td>{{ book.purchase_date }}</td>
    <td>{{ book.loaned }}</td>
  </tr>
  {% endfor %}
  </table>
    {% if action == 'loan' %}
    <input class="w3-input" type="text" name="recipient">
	      <label>{% trans 'Borrower' %}</label>
    {% endif %}
    <br/><br/>
    <button type="submit" class="w3-button w3-green w3-hover-black w3-block">{{ button_text }}</button>
</form>
</div>
{% elif response %}
<p>
    {{ response }}
</p>
{% endif %}
{% endblock %}

library/templates/library/choose_loan.html
{% extends "library/base.html" %}
{% block content %}
{% load i18n %}
{% if loans %}
<div class="w3-margin small-font">
  <form class="w3-container" action="{% url 'library:return_book' %}" method='post'>
  {% csrf_token %}
  <table class="w3-table-all w3-hoverable">
  {% if table_headers %}
  <tr class="choose-table w3-cyan">
    <th>#</th>
    <th>{{ table_headers.recipient }}</th>
    <th>{{ table_headers.book }}</th>
    <th>{{ table_headers.loan_date }}</th>
  </tr>
  {% endif %}
  {% for loan in loans %}
  <tr class="w3-white">
    <th>
    <input type='radio' name='loanID' value='{{ loan.id }}'>
    </th>
    <th>{{ loan.recipient }}</th>
    <th>{{ loan.book }}</th>
    <th>{{ loan.loan_date }}</th>
  </tr>
  {% endfor %}
  </table>
    <br/><br/>
    <button type="submit" class="w3-button w3-green w3-hover-black w3-block">{{ button_text }}</button>
</form>
{% elif response %}
<p>
    {{ response }}
</p>
</div>
{% endif %}
{% endblock %}

library/templates/library/choose_location.html
{% extends "library/base.html" %}
{% block content %}
{% load i18n %}
{% if locations %}
  {% if action == 'new' %}
  <form class="w3-container" action="{% url 'library:new_location' %}" method='post'>
  {% elif action == 'modify' %}
  <form class="w3-container" action="{% url 'library:modify_location'%}" method='post'>
  {% elif action == 'delete' %}
  <form class="w3-container" action="{% url 'library:delete_location'%}" method='post'>
  {% endif %}
  {% csrf_token %}
  <table class="w3-table-all w3-hoverable" style="font-size:1.5vw">
  {% if table_headers %}
  <tr class="choose-table w3-cyan">
    <th>#</th>
    <th>{{ table_headers.address }}</th>
    <th>{{ table_headers.room }}</th>
    <th>{{ table_headers.furniture }}</th>
    <th>{{ table_headers.details }}</th>
  </tr>
  {% endif %}
  {% for location in locations %}
  <tr class="w3-white">
    <th>
    <input type='radio' name='locationID' value='{{ location.id }}'>
    </th>
    <th>{{ location.address }}</th>
    <th>{{ location.room }}</th>
    <th>{{ location.furniture }}</th>
    <th>{{ location.details }}</th>
  </tr>
  {% endfor %}
  </table>
    <br/><br/>
    <button type="submit" class="w3-button w3-green w3-hover-black w3-block">{{ button_text }}</button>
</form>
{% elif response %}
<p>
    {{ response }}
</p>
{% endif %}
{% endblock %}

library/templates/library/home.html
{% extends "library/base.html" %}
{% block content %}
{% load i18n %}
<div class=" home w3-container w3-card-4 w3-margin-top">
    <div class="user-info" >
    <p >{% trans 'Hello' %} {{ user.username }}</p>
    <p>{% trans 'This is a summary of your book collection' %}:</p>
    <ul>
        <li>{% trans 'Total books' %}: {{ books }}</li>
        <li>{% trans 'Pending loans' %}: {{ loans }}</li>
    </ul>
    <br/>
    </div>
    <br/>
    <a class="logout" href="{% url 'library:log_me_out' %}">{% trans 'Log out' %}</a>
</div>
{% endblock %}

library/templates/library/location_info.html
{% extends "library/base.html" %}
{% block content %}
{% load i18n %}
{% if response %}
  <p>
  {{ response }}
  </p>
{% else %}
  <div  class="w3-container small-font w3-teal">
      <div class="w3-container">
         <h2 align="center" >{% trans 'Location Information' %}</h2>
	  </div>
      <div class="w3-container">
	  <form action="{% url 'library:location_info' location.id %}" method='post'>
            {% csrf_token %}
            <input type='hidden' name='locationID' value='{{location.id}}'>
		  <label>{% trans 'Address' %}</label>
		  <input class="w3-input" type="text" name="address"  value="{{location.address}}">
          <label>{% trans 'Room' %}</label>
  		  <input class="w3-input" type="text" name="room" value="{{location.room}}">
  		  <label>{% trans 'Furniture' %}</label>
  		  <input class="w3-input" type="text" name="furniture" value="{{location.furniture}}">
  		  <label>{% trans 'Details' %}</label>
  		  <input class="w3-input" type="text" name="details" value="{{location.details}}">
			<br/>
	<div class="medium-font w3-cell-row w3-black">
  		<button type="submit" name="action" value="modify" class="w3-half w3-container w3-cell w3-btn w3-mobile w3-hover-green">{% trans 'Modify'%}</button>
		<button type="submit" name="action" value="delete" class="w3-half w3-container w3-cell w3-btn w3-mobile w3-hover-green">{% trans 'Delete'%}</button>
	</div>
		</form>
    </div>
  </div>
{% endif %}
<br/>
{% endblock %}

library/templates/library/login.html
{% extends "library/base.html" %}
{% block content %}
{% load i18n %}
<!-- LOGIN TEMPLATE -->
<div>
 {% if form.errors %}
<p>{% trans "Your username and password didn't match. Please try again." %}</p>
{% endif %}
  {% if next %}
    {% if user.is_authenticated %}
      <p>{% trans "Your account doesn't have access to this page. To proceed,
    please login with an account that has access." %}</p>
    {% else %}
    
  {% endif %}
{% endif %}
<div class="login w3-container w3-card-4 w3-margin-top">
    <form action="{% url 'login' %}" method="post">
        <br/>
        <p>{% trans 'Please login to see this page.' %}</p>
        <br/>
          {% csrf_token %}
          <table>
            <tr>
                <td>{{ form.username.label_tag }}</td>
                <td>{{ form.username }}</td>
            </tr>
            <tr>
                <td>{{ form.password.label_tag }}</td>
                <td>{{ form.password }}</td>
            </tr>
          </table>
          <br/>
          <input type="submit" value="login">
          <input type="hidden" name="next" value="{{ next }}">
        <br/>
    <br/>
        <p>{% trans 'Not signed up yet???' %}</p>
        <a href="{% url 'library:signup' %}">{% trans 'Sign up here!!' %}</a>
    </form>
</div>
</div>
{% endblock %}

library/templates/library/new_location.html
{% extends "library/base.html" %}
{% block content %}
{% load i18n %}
  <div  class="w3-container small-font w3-teal">
      <div class="w3-container">
          <h2 align="center" >{% trans 'Add new Location to Database' %}</h2>
	  </div>
      <div class="w3-container">
		<form class="w3-container" action="{% url 'library:new_location' %}" method='post'>
            {% csrf_token %}
		  <label>{% trans 'Address' %}</label>
		  <input class="w3-input" type="text" name="address">
          <label>{% trans 'Room' %}</label>
  		  <input class="w3-input" type="text" name="room">
  		  <label>{% trans 'Furniture' %}</label>
  		  <input class="w3-input" type="text" name="furniture">
  		  <label>{% trans 'Details' %}</label>
  		  <input class="w3-input" type="text" name="details">
			<br/>
  		  <button class="medium-font w3-button w3-block w3-hover-black w3-green">{% trans 'Add New Location' %}</button>
			<br>
		</form>
      </div>
    </div>
{% endblock %}

library/templates/library/show_books.html
{% extends "library/base.html" %}
{% block content %}
<!-- SHOW BOOKS -->
<div class="w3-margin small-font">
  <table id="books" class="w3-table-all w3-hoverable ">
    {% if table_headers %}
  <tr class="w3-cyan">
    <th class="w3-hover-light-blue ">{{ table_headers.title }}</th>
    <th class="w3-hover-light-blue">{{ table_headers.author }}</th>
    <th class="w3-hover-light-blue">{{ table_headers.genre }}</th>
    <th class="w3-hover-light-blue">{{ table_headers.publisher }}</th>
    <th class="w3-hover-light-blue">{{ table_headers.publish_date }}</th>
    <th class="w3-hover-light-blue">{{ table_headers.purchase_date }}</th>
    <th class="w3-hover-light-blue">{{ table_headers.loaned }}</th>
  </tr>
    {% endif %}
    {% if books %}
    {% for book in books %}
    <tr id="{{book.id}}" onclick="location.href='/books/{{book.id}}/';" class="book-row w3-white w3-hover-pale-red">
      <td>{{ book.title }}</td>
      <td>{{ book.author }}</td>
      <td>{{ book.genre }}</td>
      <td>{{ book.publisher }}</td>
      <td>{{ book.publish_date }}</td>
      <td>{{ book.purchase_date }}</td>
      <td>{{ book.loaned }}</td>
    </tr>
    {% endfor %}
    {% endif %}
  </table>
</div>
{% endblock %}

library/templates/library/show_loans.html
{% extends "library/base.html" %}
{% block content %}
<!-- SHOW LOANS -->
<div class="w3-margin small-font">
  <table class="w3-table-all w3-hoverable">
    {% if table_headers %}
  <tr class="w3-cyan">
    <th>{{ table_headers.book }}</th>
    <th>{{ table_headers.recipient }}</th>
    <th>{{ table_headers.loan_date }}</th>
    <th>{{ table_headers.return_date }}</th>
  </tr>
    {% endif %}
    {% if loans %}
    {% for loan in loans %}
    <tr class="w3-white">
      <td>{{ loan.book }}</td>
      <td>{{ loan.recipient }}</td>
      <td>{{ loan.loan_date }}</td>
      <td>{{ loan.return_date }}</td>
    </tr>
    {% endfor %}
    {% endif %}
  </table>
</div>
{% endblock %}

library/templates/library/show_locations.html
{% extends "library/base.html" %}
{% block content %}
<!-- SHOW LOCATIONS -->
<div class="w3-margin small-font">
  <table id="locations" class="w3-table-all w3-hoverable">
    {% if table_headers %}
  <tr class="w3-cyan">
    <th class="w3-hover-light-blue ">{{ table_headers.address }}</th>
    <th class="w3-hover-light-blue ">{{ table_headers.room }}</th>
    <th class="w3-hover-light-blue ">{{ table_headers.furniture }}</th>
    <th class="w3-hover-light-blue ">{{ table_headers.details }}</th>
  </tr>
    {% endif %}
    {% if locations %}
    {% for location in locations %}
    <tr class="w3-white w3-hover-pale-red" onclick="location.href='/locations/{{location.id}}/';">
      <td>{{ location.address }}</td>
      <td>{{ location.room }}</td>
      <td>{{ location.furniture }}</td>
      <td>{{ location.details }}</td>
    </tr>
    {% endfor %}
    {% endif %}
  </table>
</div>
{% endblock %}

library/templates/library/signup.html
{% extends "library/base.html" %}
{% load i18n %}
{% block content %}
<div class="signup w3-container w3-card-4 w3-margin-top">
    <form action="{% url 'library:signup' %}" method="post">
      <br/>
      {% csrf_token %}
      {{ form.as_p }}
        <br/>
      <button type="submit">{% trans 'Sign up' %}</button>
        <br/>
        <br/>
    </form>
</div>
{% endblock %}